animations {
	enabled = true
	workspace_wraparound = false

	bezier = easeIn, 0.22, 0.63, 0.1, 1
	bezier = easeOut, 0, 0.39, 0.14, 1
	bezier = linear,0,0,1,1
	bezier = quick,0.15,0,0.1,1
	bezier = easeOutBack, 0.34, 1.56, 0.64, 1

	animation = global, 1, 5, linear
	animation = windowsIn, 1, 4, easeOut, popin
	animation = windowsOut, 1, 1, easeOut, popin 60%
	animation = windowsMove, 1, 5, easeIn, slide
	animation = layers, 1, 5, easeIn, fade
	animation = fade, 1, 5, easeIn
	animation = fadeIn, 1, 5, easeIn
	animation = fadeOut, 1, 5, easeIn
	animation = border, 0, 5, easeIn
	animation = borderangle, 1, 1, linear, once
	animation = workspaces, 1, 5, easeIn, slidevert
	animation = specialWorkspace, 1, 5, easeIn, slide
}
