hl.on("hyprland.start", function ()
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("sleep 0.5; awww img ~/.config/wallpaper.png --transition-type fade --transition-duration 1.0")
	hl.exec_cmd("udiskie")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css")
	hl.exec_cmd("exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("wl-paste --type text --watch cliphist store # Stores only text data")
	hl.exec_cmd("wl-paste --type image --watch cliphist store # Stores only image data")
	hl.exec_cmd("~/.config/hypr/scripts/battery_notifier.sh")
end)
