decoration {
    blur {
        enabled = true
        size = 2
        passes = 2
        ignore_opacity = true
        new_optimizations = true
        xray = false
        noise = 0.0117
        contrast = 0.9
        brightness = 1
        vibrancy = 0.1696
        vibrancy_darkness = 0.5
        special = false
        popups = false
        popups_ignorealpha = 0.2
        input_methods = false
        input_methods_ignorealpha = 0.2
    }
}
