hl.config({render = {
	direct_scanout = 0,
	expand_undersized_textures = true,
	xp_mode = false,
	ctm_animation = 2,
	cm_enabled = true,
	send_content_type = true,
	cm_auto_hdr = 1,
	new_render_scheduling = false,
	non_shader_cm = 2,
	non_shader_cm_interop = 2,
	cm_sdr_eotf = "default",
	commit_timing_enabled = true,
	use_fp16 = 2,
	keep_unmodified_copy = 2,
	use_shader_blur_blend = false,
}})
