decoration {
    shadow {
        enabled = true
        range = 7
        render_power = 3
        sharp = false
        ignore_window = true
        color = 0x50000000
        color_inactive = 0x50000000
        offset = 0 0
        scale = 1.0
    }
}
