input {
    touchpad {
        disable_while_typing = false
        natural_scroll = true
        scroll_factor = 1.0
        middle_button_emulation = false
        tap_button_map = 
        clickfinger_behavior = false
        tap-to-click = true
        drag_lock = 1
        tap-and-drag = true
        flip_x = false
        flip_y = false
        drag_3fg = 0
    }
}
