source = ~/.config/hypr/conf/general.conf
source = ~/.config/hypr/conf/snap.conf
source = ~/.config/hypr/conf/decoration.conf
source = ~/.config/hypr/conf/blur.conf
source = ~/.config/hypr/conf/shadow.conf
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/touchpad.conf
source = ~/.config/hypr/conf/touchdevice.conf
source = ~/.config/hypr/conf/virtualkeyboard.conf
source = ~/.config/hypr/conf/tablet.conf
source = ~/.config/hypr/conf/gestures.conf
source = ~/.config/hypr/conf/group.conf
source = ~/.config/hypr/conf/groupbar.conf
source = ~/.config/hypr/conf/misc.conf
source = ~/.config/hypr/conf/layout.conf
source = ~/.config/hypr/conf/dwindle.conf
source = ~/.config/hypr/conf/master.conf
source = ~/.config/hypr/conf/scrolling.conf
source = ~/.config/hypr/conf/binds.conf
source = ~/.config/hypr/conf/xwayland.conf
source = ~/.config/hypr/conf/opengl.conf
source = ~/.config/hypr/conf/render.conf
source = ~/.config/hypr/conf/cursor.conf
source = ~/.config/hypr/conf/ecosystem.conf
source = ~/.config/hypr/conf/quirks.conf

source = ~/.config/hypr/conf/exec.conf
source = ~/.config/hypr/conf/environment.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/bindings.conf

source = ~/.config/hypr/conf/rules.conf
